Support releasing pre-release versions
Both npm and GitHub need to have pre-release versions marked as such.

Run npm publish $DIST_FOLDER
  npm publish $DIST_FOLDER
  shell: sh -e {0}
  env:
    DIST_FOLDER: /dist/artifact
npm error You must specify a tag using --tag when publishing a prerelease version.
npm error A complete log of this run can be found in: /github/home/.npm/_logs/2026-02-17T12_48_29_010Z-debug-0.log
Error: Process completed with exit code 1.