Try to fix npm release
Run npm publish $DIST_FOLDER --tag beta
npm notice
npm notice package: gocardless-nodejs@7.2.0-beta1
npm notice Tarball Contents
npm notice 3.4kB README.md
npm notice 3.1kB package.json
npm notice Tarball Details
npm notice name: gocardless-nodejs
npm notice version: 7.2.0-beta1
npm notice filename: gocardless-nodejs-7.2.0-beta1.tgz
npm notice package size: 2.2 kB
npm notice unpacked size: 6.4 kB
npm notice shasum: 7e2a8a4de9165d4dfed94aa54c8f0658ff811221
npm notice integrity: sha512-va3UUq8qnBLQ5[...]ciUTkkfSpd5tw==
npm notice total files: 2
npm notice
npm error code ENEEDAUTH
npm error need auth This command requires you to be logged in to https://registry.npmjs.org/
npm error need auth You need to authorize this machine using `npm adduser`
npm error A complete log of this run can be found in: /github/home/.npm/_logs/2026-02-17T13_01_14_846Z-debug-0.log
Error: Process completed with exit code 1.